spring:
  profiles:
    active: production
  data:
    mongodb:
      uuid-representation: standard
      authentication-database: admin
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: lotto-web

lotto:
  winning:
    minWinNumber: 1
    maxWinNumber: 99
    winNumberCount: 6

server:
  port: 8000
