spring:
  profiles:
    active: integration
  data:
    mongodb:
      uuid-representation: standard
      authentication-database: admin
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  winning:
    minWinNumber: 1
    maxWinNumber: 99
    winNumberCount: 6

server:
  port: 8000
